### ISSUE TITLE
RuntimeError: XBMC is not playing any media file

### ISSUE THREAD

**Issue by dagwieers** [im85288/service.upnext#120]
This is something we have seen with VRT NU as well. If you're unlucky with timing you call 
`getTime()` or `getTotalTime()` when the media has stopped playing. So we ought to catch those situations and offer a clean exit.

```
2019-12-06 02:45:00.607 T:1283453824   ERROR: EXCEPTION: XBMC is not playing any media file
2019-12-06 02:45:00.609 T:1283453824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XBMC is not playing any media file
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.upnext/service.py", line 8, in <module>
                                                Monitor().run()
                                              File "/storage/.kodi/addons/service.upnext/resources/lib/monitor.py", line 68, in run
                                                self.playback_manager.launch_up_next()
                                              File "/storage/.kodi/addons/service.upnext/resources/lib/playbackmanager.py", line 39, in launch_up_next
                                                self.launch_popup(episode, playlist_item)
                                              File "/storage/.kodi/addons/service.upnext/resources/lib/playbackmanager.py", line 51, in launch_popup
                                                self.show_popup_and_wait(episode, next_up_page, still_watching_page))
                                              File "/storage/.kodi/addons/service.upnext/resources/lib/playbackmanager.py", line 75, in show_popup_and_wait
                                                play_time = self.player.getTime()
                                            RuntimeError: XBMC is not playing any media file
                                            -->End of Python script error report<--
```

I don't think this is related to reported issues, because this clearly dumps a traceback and provide a Kodi error.

**Comment by dagwieers** [comment]
However, if this happens, Up Next is no longer active. And will no longer work correctly as the service is no longer running.
